generator:
  class: sfPropelGenerator
  param:
    model_class:           Weather
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Weather
    plural:                Weathers
    route_prefix:          weather
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
