<?php


/**
 * Skeleton subclass for performing query and update operations on the 'theme_weathers' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 14 13:03:36 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ThemeWeatherPeer extends BaseThemeWeatherPeer {
  
  public static function retrieveAllByThemeId($themeId=null){
    if(empty($themeId)){
      return null;
    }
    
    $c = new Criteria();
    $c->add(self::THEME_ID, $themeId);
    // $c->addJoin(self::WEATHER_ID, WeatherPeer::ID);
    // $c->addDescendingOrderByColumn(WeatherPeer::MAX_PHOTO_NUMBER);
    $tws = self::doSelect($c);
    $ids = array();
    foreach($tws as $tw){
      array_push($ids, $tw->getWeatherId());
    }
    return WeatherPeer::retrieveByPKs($ids);
  }
} // ThemeWeatherPeer
