<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_photos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul 13 14:32:37 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserPhotoPeer extends BaseUserPhotoPeer {

  public static function getUserByPhotoId($photoId=null){
    if(empty($photoId)){
      return null;
    }
    
    $c = new Criteria();
    $c->add(self::PHOTO_ID, $photoId);
    $cp = self::doSelectOne($c);
    return UserPeer::retrieveByPK($cp->getUserId());
  }
} // UserPhotoPeer
