propel: 
  photo_comments: 
    _attributes:  {phpName: PhotoComment}
    id:
    user_id: { type: integer, foreignTable: users, foreignReference: id, onDelete: cascade, required: true, primaryKey: true }
    photo_id: { type: integer, foreignTable: photos, foreignReference: id, onDelete: cascade, required: true, primaryKey: true  }
    description: { type: longvarchar }
    created_at: ~
    updated_at: ~
