generator:
  class: sfPropelGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              User
    plural:                Users
    route_prefix:          user
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
